[build]
target = "x86_64-unknown-none"

[unstable]
bindeps = true
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
# Remove the nostartfiles flag that's causing the issue
rustflags = [
    # The following flags are more appropriate for LLVM lld
    "-C", "link-arg=-znoexecstack", 
    "-C", "link-arg=-zrelro",
    "-C", "link-arg=-znow"
]